sudo: required
services:
    - docker

before_install:
    - docker build -t lipidocker1/react-project:prod -f Dockerfile_dev .

script:
    - docker run -e CI=true lipidocker1/react-project:prod npm run test

deploy:
   provider: elasticbeanstalk
   region: us-west-1 # Specify your region
   app: "react-project-docker" # Copy it from Elastic Beanstalk dashboard
   env: "ReactProjectDocker-env" # Copy it from Elastic Beanstalk dashboard
   bucket_name: "elasticbeanstalk-us-west-1-391998522123"
   bucket_path: "docker"
   access_key_id:  $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
   on:
       branch: master
